### ISSUE TITLE
pentoo-installer fails on first step, broken repos.conf

### ISSUE THREAD

**Issue by skintigh** [pentoo/pentoo-livecd#38]
pentoo-full-amd64-hardened-2020.0_p20200819.iso

pentoo-installer fails while setting the clock because repos.conf is pointing to non existent folders like "gentoo" I tried various forms of renaming and adding new entries but it seems required subdirectories for setting the clock are missing as well. 

I changed the repos.conf back and I attempted a pentoo-update. Failed for the same reasons.

It told me to do an emerge --oneshot sys-apps/portage . That also failed.

Minor side note: checksums on a new live USB also fail if a windows machine is used to make the USB. Unetbooten changes syslinux.cfg LFs to CRLFs and some other tools do, too. I saw that mentioned but not solved in a closed ticket.

**Comment by ZeroChaos-** [comment]
this specific daily iso had a bug causing the squashfs containing those files to not be generated.  it is fixed in the iso building now.  There are other minor bugs, but none which should prevent install afaik.

As for your minor note, there is no way to tell the difference between modifying files in a "safe" way, and modifying files in a way which cause breakage.  If you can write up a list of which tools don't modify the files and break the checksum, I'll gladly add it to the FAQ.  That said, I won't be changing the way verify works, because that kind of tampering is exactly what it's try to detect.

**Comment by ZeroChaos-** [comment]
we are prepping to make a stable release but the previous stable release was so old that no one should install it so I removed it.  It's been too long between releases due to lost of gentoo changes.
